{% set name = "py" %}
{% set version = "1.11.0" %}
{% set hash = "51c75c4126074b472f746a24399ad32f6053d1b34b68d2fa41e558e6f4a98719" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/py/py-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - py
    - py.code
    - py.io
    - py.log
    - py.path
    - py.process

about:
  home: https://github.com/pytest-dev/py
  license: MIT
  license_file: LICENSE
  summary: library with cross-python path, ini-parsing, io, code, log facilities

extra:
  recipe-maintainers:
    - nicoddemus
    - jakirkham
